### ISSUE TITLE
Wallpaper download location

### ISSUE THREAD

**Issue by sarbjitbilling** [romannurik/muzei#703] opened 2021-01-03 13:58 UTC
Hi - Is it possible to access the current wallpaper programatically - i.e. from some folder?

Previously I used Muzei Saver v2.0.1 to save the current wallpaper to /storage/emulated/0/Download

I have a Tasker script that runs Muzei Saver and then copies the wallpaper to a folder on my SD Card daily.

This approach does not work in Muzei Saver v3.  It does not seem to work programtically from Tasker.

So I was hoping to access the wallpaper directly from Muzei v3.

**Comment by ianhanniballake** [comment] 2021-01-03 16:11
This looks like a duplicate of #669

Muzei's current wallpaper is always accessible via the [Muzei API](http://api.muzei.co/reference/index.html), which is what Muzei Saver, etc. should be using.

**Closed** 2021-01-03 16:12 UTC
