### ISSUE TITLE
Add Align Option

### ISSUE THREAD

**Issue by sarsa2703** [romannurik/muzei#594] opened 2019-01-01 10:16 UTC
I made an app with wallpapers. I want to support it through many device that's why the wallpapers are large in width. Is it not possible to add a little option to align the Wallpaper to Left, Center and Right? So,the wallpaper's main subject will not get cut.
I don't know if this feature was requested before. Although, Thanks for making app like this.

**Comment by sarsa2703** [comment] 2019-01-01 10:35
It

**Comment by ianhanniballake** [comment] 2019-01-02 05:11
Yup, duplicate of #13, #62, and #64

**Closed by ianhanniballake** 2019-01-02 05:11 UTC
