### ISSUE TITLE
Failing to display "about this photo" 

### ISSUE THREAD

**Issue by leophys** [romannurik/muzei#677] opened 2020-07-21 17:15 UTC
Hi, thanks for this nice app!

Since at least version `3.2.0` the section "About this photo" does not show up.

Now I have version `3.3.0` installed an the problem persists.

Relevant log line is the following:

```
07-21 19:11:11.194 E/Layer   (920): [Surface(name=AppWindowToken{30a6dcb token=Token{411509a ActivityRecord{793d145 u0 net.nurik.roman.muzei/com.google.android.apps.muzei.MuzeiActivity t32709}}})/@0xcf3c2f9 - animation-leash#0] No local sync point found
``` 

Can I assist further? 

EDIT: I am on android Q/lineageos-17.1

**Comment by ianhanniballake** [comment] 2020-07-22 01:12
Can you include a screenshot of what exactly you're talking about? What Source are you using?

**Comment by leophys** [comment] 2020-07-22 07:57
> Can you include a screenshot of what exactly you're talking about? What Source are you using?

Sure. I am using [national geographic for muzei](https://github.com/sal0max/muzei-nationalgeographic). The menu voice I am talking about is the first one in this menu, that usually showed the description retrieved in the photo's caption on the national geographic website.
![A screenshot from the app](https://user-images.githubusercontent.com/382161/88150306-82d12680-cc01-11ea-9250-d3ac54f3cb3d.png)

If this is not an issue with muzei, I will move to that app. The fact is that it seemed to me that log related to a transition issued by muzei :blush:

**Comment by leophys** [comment] 2020-07-22 10:16
I just realized that also the "Share this photo" action does not work.

Filtering by `muzei` in logcat gives these log lines:

```
07-22 11:25:34.240 I/ActivityManager(1023): Start proc 28451:de.msal.muzei.nationalgeographic/u0a405 for content provider {de.msal.muzei.nationalgeographic/de.msal.muzei.nationalgeographic.NationalGeographicArtProvider}
07-22 11:26:36.799 I/ActivityManager(1023): Killing 28451:de.msal.muzei.nationalgeographic/u0a405 (adj 985): empty #17
07-22 12:07:46.533 I/ActivityManager(1023): Start proc 30743:de.msal.muzei.nationalgeographic/u0a405 for content provider {de.msal.muzei.nationalgeographic/de.msal.muzei.nationalgeographic.NationalGeographicArtProvider}
07-22 12:08:14.362 I/ActivityManager(1023): Killing 30743:de.msal.muzei.nationalgeographic/u0a405 (adj 995): empty #17
07-22 12:08:39.734 I/ActivityTaskManager(1023): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=net.nurik.roman.muzei cmp=net.nurik.roman.muzei/com.google.android.apps.muzei.MuzeiActivity} from uid 10424
07-22 12:08:39.818 I/ActivityManager(1023): Start proc 31414:pro.rudloff.muzei.commons/u0a196 for content provider {pro.rudloff.muzei.commons/pro.rudloff.muzei.commons.CommonsArtProvider}
07-22 12:08:39.813 W/main    (31414): type=1400 audit(0.0:38437): avc: granted { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=12739 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file app=pro.rudloff.muzei.commons
07-22 12:08:39.830 E/f.muzei.common(31414): Not starting debugger since process cannot load the jdwp agent.
07-22 12:08:39.853 I/f.muzei.common(31414): The ClassLoaderContext is a special shared library.
07-22 12:08:39.913 W/main    (31439): type=1400 audit(0.0:38438): avc: granted { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=12739 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file app=pro.rudloff.muzei.commons
07-22 12:08:39.922 I/ActivityManager(1023): Start proc 31439:com.example.muzei.muzeiapod/u0a197 for content provider {com.example.muzei.muzeiapod/com.example.muzei.muzeiapod.ApodNasaArtSource}
07-22 12:08:39.925 E/muzei.muzeiapo(31439): Not starting debugger since process cannot load the jdwp agent.
07-22 12:08:39.942 I/muzei.muzeiapo(31439): The ClassLoaderContext is a special shared library.
07-22 12:08:39.980 I/ActivityManager(1023): Start proc 31460:de.msal.muzei.nationalgeographic/u0a405 for content provider {de.msal.muzei.nationalgeographic/de.msal.muzei.nationalgeographic.NationalGeographicArtProvider}
07-22 12:08:40.203 E/Layer   (920): [Surface(name=AppWindowToken{9724cfe token=Token{acb30b9 ActivityRecord{80cb280 u0 net.nurik.roman.muzei/com.google.android.apps.muzei.MuzeiActivity t32759}}})/@0x1bdcfe5 - animation-leash#0] No local sync point found
07-22 12:08:51.312 W/ActivityTaskManager(1023): Background activity start [callingPackage: de.msal.muzei.nationalgeographic; callingUid: 10405; isCallingUidForeground: false; isCallingUidPersistentSystemProcess: false; realCallingUid: 10405; isRealCallingUidForeground: false; isRealCallingUidPersistentSystemProcess: false; originatingPendingIntent: null; isBgStartWhitelisted: false; intent: Intent { act=android.intent.action.CHOOSER flg=0x10000000 cmp=android/com.android.internal.app.ChooserActivity (has extras) }; callerApp: ProcessRecord{8997378 31460:de.msal.muzei.nationalgeographic/u0a405}]
07-22 12:10:45.275 I/ActivityManager(1023): Killing 31414:pro.rudloff.muzei.commons/u0a196 (adj 985): empty #17
07-22 12:11:15.170 I/ActivityManager(1023): Killing 31439:com.example.muzei.muzeiapod/u0a197 (adj 985): empty #17
07-22 12:11:15.252 I/ActivityManager(1023): Killing 31460:de.msal.muzei.nationalgeographic/u0a405 (adj 985): empty #17
```

Maybe it's an issue related to `de.msal.muzei.nationalgeographic` and is not due to muzei, but I am not able to tell.

**Comment by ianhanniballake** [comment] 2020-07-23 01:31
Yeah, those are actions provided by the National Geographic source. The issue you're experiencing is caused by the extension using an older version of Muzei's API. In particularly, the issue with actions on Android 10+ was fixed in [Muzei API 3.4.0-alpha01](https://github.com/romannurik/muzei/releases/tag/api3.4.0-alpha1) with the new `getCommandActions()` API.

You'll want to file an issue / contact the National Geographic source to have them upgrade to the Muzei API 3.4.

**Closed by ianhanniballake** 2020-07-23 01:31 UTC

**Comment by ianhanniballake** [comment] 2020-07-23 05:59
Since the National Geographic Source is on Github, I [made a pull request](https://github.com/sal0max/muzei-nationalgeographic/pull/10) to upgrade them to the Muzei API 3.4. Hopefully they'll merge the pull request and release a new version to fix your issue.

**Comment by leophys** [comment] 2020-07-23 07:06
Thank you very much! I appreciate your work!
